services:

  postgres:
    image: postgres:16

    container_name: spotify_postgres

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl:
    build: .
    container_name: spotify_etl
    depends_on:
      - postgres
    env_file:
      - .env

  metabase:
    image: metabase/metabase
    container_name: spotify_metabase
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase-data
    depends_on:
      - postgres

volumes:
  postgres_data:
  metabase_data:
